/*----------------------------------------------------------------------------*/
/* COPYRIGHT: MINIXJR (c) 2024-2026 / TTCut-ng                               */
/*----------------------------------------------------------------------------*/
/* PROJEKT  : TTCUT 2026                                                      */
/* FILE     : ttesinfo.h                                                      */
/*----------------------------------------------------------------------------*/
/* AUTHOR  : MINIXJR                                           DATE: 01/2026  */
/*----------------------------------------------------------------------------*/

// ----------------------------------------------------------------------------
// TTESINFO
// Parser for TTCut Elementary Stream Info files (.info)
// These files are generated by ts_demux_normalize.sh and contain metadata
// about demuxed elementary streams (frame rate, dimensions, etc.)
// ----------------------------------------------------------------------------

/*----------------------------------------------------------------------------*/
/* This program is free software; you can redistribute it and/or modify it    */
/* under the terms of the GNU General Public License as published by the Free */
/* Software Foundation;                                                       */
/* either version 3 of the License, or (at your option) any later version.    */
/*----------------------------------------------------------------------------*/

#ifndef TTESINFO_H
#define TTESINFO_H

#include <QString>
#include <QFileInfo>
#include <QStringList>
#include <QMap>

// ----------------------------------------------------------------------------
// Audio track info from .info file
// ----------------------------------------------------------------------------
struct TTAudioTrackInfo {
    QString file;
    QString codec;
    QString language;
};

// ----------------------------------------------------------------------------
// VDR Marker info from .info file (from markad plugin)
// ----------------------------------------------------------------------------
struct TTMarkerInfo {
    QString timestamp;   // Format: H:MM:SS.FF
    int frame;           // Frame number
    QString type;        // "start" (content starts), "stop" (content stops), "mark" (unknown)
    bool verified;       // Whether markad verified this marker

    // Convert timestamp to milliseconds
    int toMilliseconds() const;
    // Convert timestamp to frame number (if frame is 0, calculate from timestamp and fps)
    int toFrame(double fps) const;
};

// ----------------------------------------------------------------------------
// TTESInfo class
// Parses .info files generated by ts_demux_normalize.sh
// ----------------------------------------------------------------------------
class TTESInfo
{
public:
    TTESInfo();
    explicit TTESInfo(const QString& infoFilePath);

    // Load info file
    bool load(const QString& infoFilePath);
    bool isLoaded() const { return mLoaded; }

    // Find .info file for a video file
    // E.g., for "video.264" looks for "video.info" or matching base name
    static QString findInfoFile(const QString& videoFilePath);

    // Video info
    QString videoFile() const { return mVideoFile; }
    QString videoCodec() const { return mVideoCodec; }
    int videoWidth() const { return mVideoWidth; }
    int videoHeight() const { return mVideoHeight; }

    // Frame rate as rational (numerator/denominator)
    int frameRateNum() const { return mFrameRateNum; }
    int frameRateDen() const { return mFrameRateDen; }
    double frameRate() const;

    // Frame duration in various time bases
    double frameDurationSeconds() const;
    int64_t frameDurationInTimeBase(int64_t timeBase) const;

    // Original PTS start (for offset correction)
    double startPts() const { return mStartPts; }

    // Filler info
    bool fillerStripped() const { return mFillerStripped; }
    int64_t fillerSavedBytes() const { return mFillerSavedBytes; }

    // Audio tracks
    int audioTrackCount() const { return mAudioTracks.size(); }
    TTAudioTrackInfo audioTrack(int index) const;
    QStringList audioFiles() const;

    // Source file
    QString sourceFile() const { return mSourceFile; }

    // VDR Markers (from markad plugin)
    int markerCount() const { return mMarkers.size(); }
    TTMarkerInfo marker(int index) const;
    QList<TTMarkerInfo> markers() const { return mMarkers; }
    bool hasMarkers() const { return !mMarkers.isEmpty(); }

    // Timing info (A/V sync offset)
    double firstVideoPts() const { return mFirstVideoPts; }
    double firstAudioPts() const { return mFirstAudioPts; }
    int avOffsetMs() const { return mAvOffsetMs; }
    bool hasTimingInfo() const { return mHasTimingInfo; }

    // Error handling
    QString lastError() const { return mLastError; }

private:
    bool parseSection(const QString& section, const QMap<QString, QString>& values);
    bool parseFrameRate(const QString& frameRateStr);

    bool mLoaded;
    QString mLastError;

    // Source info
    QString mSourceFile;

    // Video info
    QString mVideoFile;
    QString mVideoCodec;
    int mVideoWidth;
    int mVideoHeight;
    int mFrameRateNum;
    int mFrameRateDen;
    double mStartPts;
    bool mFillerStripped;
    int64_t mFillerSavedBytes;

    // Audio tracks
    QList<TTAudioTrackInfo> mAudioTracks;

    // VDR Markers
    QList<TTMarkerInfo> mMarkers;

    // Timing info (A/V sync)
    bool mHasTimingInfo;
    double mFirstVideoPts;
    double mFirstAudioPts;
    int mAvOffsetMs;
};

#endif // TTESINFO_H
