/*----------------------------------------------------------------------------*/
/* SPDX-License-Identifier: GPL-3.0-or-later                                  */
/*                                                                            */
/* TTCut-ng - frame-accurate video cutter                                     */
/* Copyright (c) 2024-2026 MINIXJR                                            */
/*                                                                            */
/* Free software under the GNU GPL v3 or later - see the LICENSE file.        */
/*----------------------------------------------------------------------------*/

// ----------------------------------------------------------------------------
// TTESINFO
// Parser for TTCut Elementary Stream Info files (.info)
// These files are generated by ttcut-demux and contain metadata
// about demuxed elementary streams (frame rate, dimensions, etc.)
// ----------------------------------------------------------------------------

#ifndef TTESINFO_H
#define TTESINFO_H

#include <QString>
#include <QFileInfo>
#include <QStringList>
#include <QMap>

// ----------------------------------------------------------------------------
// Audio track info from .info file
// ----------------------------------------------------------------------------
struct TTAudioTrackInfo {
    QString file;
    QString codec;
    QString language;
    double  firstPts   = 0.0;  // PTS of first audio frame (from .info audio_N_first_pts)
    int     trimmedMs  = 0;    // Milliseconds trimmed from start (from .info audio_N_trimmed_ms)
    int     silenceMs  = 0;    // Milliseconds of silence inserted for gap-fill repair (audio_N_silence_ms)
    int     removedMs  = 0;    // Milliseconds removed to correct A/V drift (audio_N_removed_ms)
};

// ----------------------------------------------------------------------------
// VDR Marker info from .info file (from markad plugin)
// ----------------------------------------------------------------------------
struct TTMarkerInfo {
    QString timestamp;   // Format: H:MM:SS.FF
    int frame;           // Frame number
    QString type;        // "start" (content starts), "stop" (content stops), "mark" (unknown)
    bool verified;       // Whether markad verified this marker

    // Convert timestamp to milliseconds
    int toMilliseconds() const;
    // Convert timestamp to frame number (if frame is 0, calculate from timestamp and fps)
    int toFrame(double fps) const;
};

// ----------------------------------------------------------------------------
// Decode error region from .info file
// ----------------------------------------------------------------------------
struct TTDecodeErrorRegion {
    int frame;          // Approximate frame number
    QString time;       // Approximate timestamp (HH:MM:SS.FF)
    int errorCount;     // Number of errors in this region
};

// ----------------------------------------------------------------------------
// Frame range from .info file (mid-stream gap repair / corruption reporting)
// ----------------------------------------------------------------------------
struct TTESRange {
    int start;   // First affected frame index (decode order)
    int end;     // Last affected frame index (decode order, inclusive)
    int ms;      // Duration in milliseconds, -1 when unknown
};

// ----------------------------------------------------------------------------
// TTESInfo class
// Parses .info files generated by ttcut-demux
// ----------------------------------------------------------------------------
class TTESInfo
{
public:
    TTESInfo();
    explicit TTESInfo(const QString& infoFilePath);

    // Load info file
    bool load(const QString& infoFilePath);
    bool isLoaded() const { return mLoaded; }

    // Find .info file for a video file
    // E.g., for "video.264" looks for "video.info" or matching base name
    static QString findInfoFile(const QString& videoFilePath);

    // Video info
    QString videoFile() const { return mVideoFile; }
    QString videoCodec() const { return mVideoCodec; }
    int videoWidth() const { return mVideoWidth; }
    int videoHeight() const { return mVideoHeight; }

    // Frame rate as rational (numerator/denominator)
    int frameRateNum() const { return mFrameRateNum; }
    int frameRateDen() const { return mFrameRateDen; }
    double frameRate() const;

    // Original PTS start (for offset correction)
    double startPts() const { return mStartPts; }

    // Filler info
    bool fillerStripped() const { return mFillerStripped; }
    int64_t fillerSavedBytes() const { return mFillerSavedBytes; }

    // Audio tracks
    int audioTrackCount() const { return mAudioTracks.size(); }
    TTAudioTrackInfo audioTrack(int index) const;

    // Source file
    QString sourceFile() const { return mSourceFile; }

    // VDR Markers (from markad plugin)
    int markerCount() const { return mMarkers.size(); }
    QList<TTMarkerInfo> markers() const { return mMarkers; }
    bool hasMarkers() const { return !mMarkers.isEmpty(); }

    // Timing info (A/V sync offset)
    double firstVideoPts() const { return mFirstVideoPts; }
    double firstAudioPts() const { return mFirstAudioPts; }
    int avOffsetMs() const { return mAvOffsetMs; }
    bool hasTimingInfo() const { return mHasTimingInfo; }

    // Warnings (decode errors from demux)
    bool hasWarnings() const { return mHasWarnings; }
    int decodeErrors() const { return mDecodeErrors; }
    bool recommendProjectX() const { return mRecommendProjectX; }
    QList<TTDecodeErrorRegion> decodeErrorRegions() const { return mDecodeErrorRegions; }

    // Doubled-PTS candidate AUs (from ttcut-pts-analyze via ttcut-demux).
    // Raw AU numbering of the analyzed TS (one AU per PES packet; PAFF
    // fields count separately). esTotalAus() is the guard value: consumers
    // must verify it against their own raw packet count before applying
    // the candidate positions. -1 / empty when the .info lacks the keys.
    int        esTotalAus() const { return mEsTotalAus; }
    QList<int> esDoubledPtsAus() const { return mEsDoubledPtsAus; }

    // Audio gap frame indices (from ttcut-demux audio-gap detection).
    // Used for marker visualization only — NOT for audio cut time correction.
    QList<int> audioGapFrames() const { return mAudioGapFrames; }
    int        audioGapFrameCount() const { return mAudioGapFrames.size(); }

    // Mid-stream ES gap-fill ranges (from ttcut-demux repair, .info es_missing_ranges).
    // start/end are decode-order frame indices; ms is the filled duration.
    QList<TTESRange> esMissingRanges() const { return mEsMissingRanges; }

    // Corrupt-but-retained frame ranges (from ttcut-demux repair, .info
    // corrupt_frame_ranges). No duration is reported for these -> ms == -1.
    QList<TTESRange> corruptFrameRanges() const { return mCorruptRanges; }

    // Per-track audio repair balance (from .info audio_N_silence_ms /
    // audio_N_removed_ms). 0 when the track has no repair entry.
    int audioSilenceMs(int track) const;
    int audioRemovedMs(int track) const;

    // Error handling
    QString lastError() const { return mLastError; }

private:
    bool parseSection(const QString& section, const QMap<QString, QString>& values);
    bool parseFrameRate(const QString& frameRateStr);

    bool mLoaded;
    QString mLastError;

    // Source info
    QString mSourceFile;

    // Video info
    QString mVideoFile;
    QString mVideoCodec;
    int mVideoWidth;
    int mVideoHeight;
    int mFrameRateNum;
    int mFrameRateDen;
    double mStartPts;
    bool mFillerStripped;
    int64_t mFillerSavedBytes;

    // Audio tracks
    QList<TTAudioTrackInfo> mAudioTracks;

    // VDR Markers
    QList<TTMarkerInfo> mMarkers;

    // Timing info (A/V sync)
    bool mHasTimingInfo;
    double mFirstVideoPts;
    double mFirstAudioPts;
    int mAvOffsetMs;

    // Warnings (decode errors)
    bool mHasWarnings;
    int mDecodeErrors;
    int mDecodeErrorRegionCount;
    bool mRecommendProjectX;
    QList<TTDecodeErrorRegion> mDecodeErrorRegions;

    // Extra frame indices (from ttcut-pts-analyze via ttcut-demux)
    int        mEsTotalAus = -1;    // raw AU count of the analyzed TS (-1 = key absent)
    QList<int> mEsDoubledPtsAus;    // doubled-PTS candidate AUs (raw AU numbering)

    // Audio gap frame indices (from ttcut-demux audio-gap detection)
    QList<int> mAudioGapFrames;  // sorted list of frame indices spanning audio gaps

    // Mid-stream ES gap-fill / corruption ranges (from ttcut-demux repair)
    QList<TTESRange> mEsMissingRanges;  // gap-fill ranges with filled duration (es_missing_ranges)
    QList<TTESRange> mCorruptRanges;    // corrupt-but-retained ranges, ms always -1 (corrupt_frame_ranges)
};

#endif // TTESINFO_H
